Repository mizarc/bell-claims, pull requests merged in 2024-09, with the labels that each got.

#39 Changed piston flag behaviour to only cancel pistons used from outside the claim
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt
Labels: enhancement

#40 Fixed bypassing protections when placing fluids by clicking through entities
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
Labels: bug

#41 Added protection against placing paintings in claims
  .idea/modules.xml
  .idea/modules/BellClaims.main.iml
  .idea/modules/BellClaims.test.iml
  CHANGELOG.md
  build.gradle.kts
  settings.gradle.kts
  src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PermissionBehaviour.kt
  src/main/resources/plugin.yml
Labels: enhancement

#42 Tweaked minimum partition size to 3x3
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImpl.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt
Labels: enhancement

#44 Fixed the creation of 1 block wide partitions
  CHANGELOG.md
  build.gradle.kts
  src/main/kotlin/dev/mizarc/bellclaims/domain/partitions/Area.kt
  src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImpl.kt
  src/main/resources/plugin.yml
  src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImplTest.kt
Labels: bug

#43 Language files system
  src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt
  src/main/kotlin/dev/mizarc/bellclaims/infrastructure/ClaimTool.kt
  src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/Config.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/commands/ClaimCommand.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/EditToolMenu.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/GetTranslation.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/PermissionDisplay.kt
  src/main/resources/config.yml
  src/main/resources/lang_CN.yml
  src/main/resources/lang_DE.yml
  src/main/resources/lang_EN.yml
  src/main/resources/lang_RU.yml
Labels: enhancement

#45 Disable skeleton griefing Item Frames / Paitings
  src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
Labels: enhancement

#46 Check horse passenger for permission
  src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt
Labels: enhancement

#48 Fixed multiblock protection & protection priority
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimInteractListener.kt
Labels: bug

#53 Protect passive mobs from direct hits by hostile mobs
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
Labels: bug, enhancement

#55 Fixed shift right clicking deleting player's items in menus
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimListMenu.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/EditToolMenu.kt
Labels: bug

#60 Added new flag to handle dispenser protection
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt
  src/main/resources/lang_EN.yml
Labels: enhancement

#62 Added protection against using sponge to drain claim fluids
  src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt
  src/main/resources/lang_EN.yml
Labels: enhancement

#65 Add various lightning protections for flag and permission
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt
  src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt
  src/main/resources/lang_EN.yml
Labels: enhancement

#69 Added new protection flag against falling block launching
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt
  src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/BlockLaunchListener.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/ClaimFlagDisplay.kt
  src/main/resources/lang_EN.yml
Labels: enhancement

#71 Added protection against splash and lingering potions
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/domain/flags/Flag.kt
  src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt
Labels: enhancement

#72 Added protection against sleeping in beds or setting spawn points at respawn anchors
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/domain/permissions/ClaimPermission.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/PermissionBehaviour.kt
  src/main/kotlin/dev/mizarc/bellclaims/utils/PermissionDisplay.kt
  src/main/resources/lang_EN.yml
Labels: enhancement

#73 Fixed dispensers not working in claims at all
  src/main/kotlin/dev/mizarc/bellclaims/interaction/behaviours/FlagBehaviour.kt
Labels: bug

#74 Add minimum partition and initial claim size options in the config
  CHANGELOG.md
  src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt
  src/main/kotlin/dev/mizarc/bellclaims/infrastructure/persistence/Config.kt
  src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/ClaimWorldServiceImpl.kt
  src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImpl.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/EditToolListener.kt
  src/main/resources/config.yml
  src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/ClaimWorldServiceImplTest.kt
  src/test/kotlin/dev/mizarc/bellclaims/infrastructure/services/PartitionServiceImplTest.kt
Labels: enhancement

#75 Add claim transfer option
  src/main/kotlin/dev/mizarc/bellclaims/BellClaims.kt
  src/main/kotlin/dev/mizarc/bellclaims/api/ClaimService.kt
  src/main/kotlin/dev/mizarc/bellclaims/domain/claims/Claim.kt
  src/main/kotlin/dev/mizarc/bellclaims/domain/players/PlayerState.kt
  src/main/kotlin/dev/mizarc/bellclaims/infrastructure/services/ClaimServiceImpl.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/ClaimBellListener.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/MoveToolListener.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/listeners/PlayerStateListener.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ClaimManagementMenu.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/ConfirmationMenu.kt
  src/main/kotlin/dev/mizarc/bellclaims/interaction/menus/EditToolMenu.kt
  src/main/resources/lang_EN.yml
Labels: enhancement
